apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
spec:
  to:
    kind: Service
    name: foodle-frontend
  port:
    targetPort: 3000

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: core-route
spec:
  to:
    kind: Service
    name: foodle-core
  port:
    targetPort: 3000